### ISSUE TITLE
Создать через сигналы корутину отправляющую сообщение о назначенном занятии

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#104]
# Зачем?

Это сообщение необходимо отправлять сразу обеим сторонам, после того, как создали объект Lesson

![2024-06-04_15-37](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/69113745/ec20cb77-4fad-463c-bd6b-279c8fcb5618)

# Как нужно делать?

При помощи сигнала ловить сохранение модели Lesson и передавать контекст уже в сообщение для обеих сторон.

# Где?

src/schooling
src/bot

**Comment by KonstantinRaikhert** [comment]
@Neizalik Есть успехи?

**Comment by Neizalik** [comment]
> @Neizalik Есть успехи?

Вроде сделал, но пока не могу развернуть и проверить

**Comment by Neizalik** [comment]
![image](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/171576364/3d03af3e-3a47-419a-a63e-fa15b8535d7a)

**Comment by KonstantinRaikhert** [comment]
> > @Neizalik Есть успехи?
> 
> Вроде сделал, но пока не могу развернуть и проверить

Почему не можешь?
Тут надо ускоряться) Если есть проблемы - создавай тред в пачке, будем решать

**Comment by Neizalik** [comment]
> 
> Почему не можешь? Тут надо ускоряться) Если есть проблемы - создавай тред в пачке, будем решать
Ничего такого, просто чистил комп, и лишнее задел, к вечеру починю и либо сегодня вечером либо завтра утром запулю
