### ISSUE TITLE
Реализовать страницу (шаблон) с расписанием занятий.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#110]
# Зачем?

У нас сейчас готовится ендпоинт по таске #89 и для него нужен шаблон, который для каждого пользователя будет выводить расписание занятий на неделю.

Мне кажется необходимо реализовать 2 вида: для учителя и ученика
![2024-06-05_16-27](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/69113745/3df2d7e1-d18a-4ded-80ed-02ade3b91371)

# Как нужно делать?

У всех должны отображаться дата, день недели и время. Для учеников: название предмета, преподаватель.
Для учителей: название предмета, ученик, учебный класс

# Где?

src/templates

**Comment by KonstantinRaikhert** [comment]
@serega-zhulanov Привет, ты начал реализовывать какой нибудь шаблон в рамках своей таски?

**Comment by Dmitry145528** [comment]
Привет, сейчас начну.
