### ISSUE TITLE
Настроить VPS и CD нашего приложения

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#116]
# Зачем?

Нам выделили сервер и мы наконец можем реализовать наш стейдж.

# Как нужно делать?

- сначала необходимо настроить VPS (ssh workshop@158.160.168.181). Думаю необходимо разделить пользователей и создать нового пользователя **develop**. Для него настроить необходимые права доступа и докер
- при помощи docker-compose провести настройку контейнеров с приложением
- написать workflow для доставки приложения на сервер.
- настроить ssl сертификаты (jetrai.ru домен)

# Где?

.github/workflows
infra/dev

**Comment by sergey-xx** [comment]
@KonstantinRaikhert пара вопросов
1. С какой ветки должно деплоиться? только с dev?
2. Деплой в отдельном файле? или внутри build_and_push_github_packages?
3. если в отдельном, какие условия? билд и пуш в этом файле продублировать?

**Comment by KonstantinRaikhert** [comment]
> @KonstantinRaikhert пара вопросов
> 
> 1. С какой ветки должно деплоиться? только с dev?
> 2. Деплой в отдельном файле? или внутри build_and_push_github_packages?
> 3. если в отдельном, какие условия? билд и пуш в этом файле продублировать?

1. Да, сейчас только с dev
2. Отдельным файлом
3. Можно пример посмотреть [тут](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/blob/develop/.github/workflows/stage_deploy.yml)

**Comment by sergey-xx** [comment]
@KonstantinRaikhert 
не могу понять, почему не срабатывает на workflows, можешь глянуть?

https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/actions/runs/9476118829/workflow

**Comment by KonstantinRaikhert** [comment]
> @KonstantinRaikhert не могу понять, почему не срабатывает на
> 
> ```
> on:
>   workflow_run:
>     workflows:
>       - Build and push Docker image
> ```
> 
> , можешь глянуть?
> 
> https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/actions/runs/9476118829/workflow
> 
> UPD
> 
> ```
> Note: This event will only trigger a workflow run if the workflow file is on the default branch.
> ```



> @KonstantinRaikhert не могу понять, почему не срабатывает на
> 
> ```
> on:
>   workflow_run:
>     workflows:
>       - Build and push Docker image
> ```
> 
> , можешь глянуть?
> 
> https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/actions/runs/9476118829/workflow
> 
> UPD
> 
> ```
> Note: This event will only trigger a workflow run if the workflow file is on the default branch.
> ```

Я могу поставить dev как дефолтную ветку, но может тут другой способ найдем? Мы же в main будем тоже пушить уже прод версию

**Comment by sergey-xx** [comment]
я так понимаю, нужно что бы файл появился в дефолтной ветке и затем будет работать в любой (исходя из текста)
