### ISSUE TITLE
Создать хендлер с формой обратной связи

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#117]
# Зачем?

Необходимо, чтобы у ученика и преподавателя была возможность через бота написать администратору (например если занятие сорвалось или не провелось). Как то мы это упустили в нашей диаграмме.

# Как нужно делать?

- создаём как отдельную команду - /report (если лучшая идея для нейминга, то не против)
- эта команда должна быть доступна только зарегистрированным пользователя
- при срабатывании данной команды предлагается написать обращение
- при успешной отработке администратору приходит письмо с содержанием subject (от кого, тема обращения) и телом обращения   

# Где?

src/bot/handlers
src/core/utils.py
src/templates/emailing

**Comment by KonstantinRaikhert** [comment]
@alexpunder Привет! Готов взять?

**Comment by alexpunder** [comment]
> [@alexpunder](https://github.com/alexpunder) Привет! Готов взять?

конечно!
