### ISSUE TITLE
Пройтись по TODO нашего проекта и выполнить те, которые уже возможно

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#118]
# Зачем?

Начинаем подчищать проект от артефактов
![2024-06-10_18-39](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/69113745/2f356c31-e699-4c41-9b24-b93a50f407ef)

# Как нужно делать?

Есть удобные плагины для поиска TODOs, например в VScode - https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree

# Где?

src

**Comment by KonstantinRaikhert** [comment]
@shkiperzero Привет! Берешь в работу?

**Comment by shkiperzero** [comment]
> @shkiperzero Привет! Берешь в работу?

Да, готов
