### ISSUE TITLE
Поправить некоторые моменты в админке (см. скрины)

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#120]
# Зачем?

Поправить некоторые моменты в админке
![2024-06-10_18-24](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/69113745/007cbef6-c135-431c-b1c5-245a49948af8)
![2024-06-10_18-25](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/69113745/da9311bb-9595-4a6b-8ada-134254b385ea)
![2024-06-10_18-27](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/69113745/d2663b37-98ca-47ca-9f7e-c3a0d6fb4a79)
![2024-06-10_18-59](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/69113745/e4e0e190-2fed-4fed-b67e-3bdc3a503931)

# Как нужно делать?

Править админку в каждом из приложений

**Comment by KonstantinRaikhert** [comment]
@frailtynine Привет! Возьмешь?

**Comment by frailtynine** [comment]
@KonstantinRaikhert ага, беру в работу
