### ISSUE TITLE
Поправить админку для администраторов

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#121]
# Зачем?

На скринах постарался указать, что необходимо
![2024-06-10_19-11](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/69113745/3f3c92f8-8ac0-452c-bde5-6d35a3251606)
![2024-06-10_19-12](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/69113745/81babd0e-4156-4452-89cb-184211604657)
![2024-06-10_19-12_1](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/69113745/1dcb5a15-d519-4d5b-b79a-f97fe3d1b69d)

# Где?

src/admin_user/admin.py

**Comment by KonstantinRaikhert** [comment]
@Neizalik А эта получится?

**Comment by Neizalik** [comment]
> @Neizalik А эта получится?

![image](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/171576364/db4fd680-1568-4910-bec7-813f233e1204)

Если сделать не редактируемыми, то съезжают поля, нужно во фронте подкорректировать

**Comment by KonstantinRaikhert** [comment]
> > @Neizalik А эта получится?
> 
> ![image](https://private-user-images.githubusercontent.com/171576364/338705124-db4fd680-1568-4910-bec7-813f233e1204.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyODYxMjAsIm5iZiI6MTcxODI4NTgyMCwicGF0aCI6Ii8xNzE1NzYzNjQvMzM4NzA1MTI0LWRiNGZkNjgwLTE1NjgtNDkxMC1iZWM3LTgxM2YyMzNlMTIwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QxMzM3MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNGU4YjQ2Y2Q0NTMxZTA0YWVlYmFhNWY2N2MzOGFkOTFlNTVmOGY1ZDI5OTRjNmZlZjY4NjlhZmM5ZmE3OTU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XfwWcjAnT0n7_qlhYEQ9aFW-GummQCi9mLvJZkK33d4)
> 
> Если сделать не редактируемыми, то съезжают поля, нужно во фронте подкорректировать

Найди пожалуйста этот шаблон, а мы попросим нашего фронта подкорректировать
