### ISSUE TITLE
Сделать шаблон на карточку занятия с кнопками "Отменить" и "Перенести"

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#126]
# Зачем?

У нас есть шикарных аккордеон, но нам нужен функционал переноса или отмены занятия. Поэтому нужна карточка занятия.
Вся информация о занятии:
Название
Предмет
Преподаватель (или студент)
Время и дата

и кнопки перенести и отменить.

**Comment by Dmitry145528** [comment]
В работе!
