### ISSUE TITLE
В админке изменить окончание занятия на продолжительность

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#140]
# Зачем?

У нас сейчас реализовано как начало занятия и конец. Логичнее будет все же сделать начало занятия и продолжительность.
И когда нам нужно будет где-то получить окончание занятия мы просто будем прибавлять к началу.
![2024-06-15_13-40](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/69113745/5a1c12c8-2f79-4a96-adb9-6511701b4d7a)

# Как нужно делать?

Думаю стоит поменять как в модели так и в админке.

# Где?

src/schooling

**Comment by KonstantinRaikhert** [comment]
@shkiperzero Привет! Задачу выполнишь?)

**Comment by shkiperzero** [comment]
> @shkiperzero Привет! Задачу выполнишь?)

Я смогу за нее приступить только в среду, если это не критично, то сделаю.

**Comment by KonstantinRaikhert** [comment]
> > @shkiperzero Привет! Задачу выполнишь?)
> 
> Я смогу за нее приступить только в среду, если это не критично, то сделаю.

Хорошо, буду ждать. Спасибо!

**Comment by shkiperzero** [comment]
> > > @shkiperzero Привет! Задачу выполнишь?)
> > 
> > 
> > Я смогу за нее приступить только в среду, если это не критично, то сделаю.
> 
> Хорошо, буду ждать. Спасибо!

У меня немного форс мажор. Не получается пока к задаче приступить. Думаю лучше снять ее с меня

**Comment by alexpunder** [comment]
@KonstantinRaikhert тут в джанго появился новый метод автогенерации поля модели: https://django.fun/docs/django/5.0/ref/models/fields/#generatedfield
можно сделать ввод длительности занятия, а поле `datetime_end` сделать `GeneratedField` на основе значения
либо заменить поле `datetime_end` на новое, а через декоратор `@property` высчитывать `datetime_end`

**Comment by KonstantinRaikhert** [comment]
@alexpunder А это круто!) То что надо. Спасибо!
@Noc0mments Обрати пожалуйста на это внимание)
