### ISSUE TITLE
Переделать экран успешного отправления заявки администратору

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#164]
# Зачем?

Очень скудный шаблон и не хватает кнопки закрыть (Ну или по другому назвать по смыслу). Так же думаю стоит унаследоваться от шаблонов со статикой на предыдущих шагах с логотипом
![2024-06-25_15-48](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/69113745/e25ef8a5-bf96-42b6-b26c-ac9ed649b7c7)

**Comment by Dmitry145528** [comment]
Я роуты прописал, но есть нюанс. Надо настроить передачу данных с формы {{new_datetime}}

**Comment by Dmitry145528** [comment]
И нужно проверить как написаны новые роуты. Так как писал их впервые.
