### ISSUE TITLE
Добавить Makefile для разработки

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#17]
# Зачем?

Данный инструмент нам поможет запускать одновременно и бота и джангу и БД одной командой

# Как нужно делать?

Посмотреть в [примере](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/blob/dev/Makefile) как это можно реализовать.
Необходимо разобраться, установить на свою машину (есть сложности на windows, подробная инструкция ниже)
Нам нужны:
- start-db
- stop-db
- clear-db
- run
- init-app

Инструкция по установке в Windows:

1. Проверить наличие wsl в системе: Следуй инструкциям
[https://code.s3.yandex.net/backend-developer/learning-materials/Инструкция_по_установке_и_настройке_WSL.pdf](https://code.s3.yandex.net/backend-developer/learning-materials/%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D0%B8%D1%8F_%D0%BF%D0%BE_%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B5_%D0%B8_%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B5_WSL.pdf)

2. Установить Docker Desktop:
https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe?utm_source=docker&utm_medium=webreferral&utm_campaign=dd-smartbutton&utm_location=module&_gl=1*1n1mv4y*_ga*MTA0MDU1NzU4NC4xNzAxODkwMjk5*_ga_XJWPQMJYHQ*MTcwNjgxNDkxNS41LjEuMTcwNjgxNDkxOS41Ni4wLjA

3. Установить Chocolate используя windows shell
(от имени администратора)!!  в консоль вставить всё, что после двоеточия целиком:
 Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

4. Запускаем VS code(Pycharm) клонируем репозиторий с гита командой:
если нет python ставим:
https://www.python.org/
если нет vs code ставим:
https://code.visualstudio.com/
Надеюсь как с гитом связь настроить знаешь
git clone git@github.com:Studio-Yandex-Practicum/adaptive_hockey_federation.git

Открываем консоль выбираем вместо powershell "wsl"
Дальше все команды в wsl терминале

5.  В консоли прописать - “choco install make”

6. Перезагрузить компьютер, либо поменять местами пункты 4 и 5

7. Открываем репу с проектом. Устанавливаем poetry https://python-poetry.org/docs/#installing-with-pipx 
(лучше установить его глобально и не мучаться больше)

8. После установки вводим команду: 
poetry config virtualenvs.in-project true

9. Чтобы установить зависимости и создать виртуальное окружение, вводим команду : poetry install

10.  Чтобы активировать виртуальное окружение, вводим команду: poetry shell

11. Дальше работаем с make

# Где?

В корне каталога

**Comment by DBratkov** [comment]
Улучшил Makefile, поправил недочеты с переменными окружения в разрезе разработки.
