### ISSUE TITLE
При одобрении заявки обрабатывать ошибку 500

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#171]
# Зачем?

Есть проблема, когда мы одобряем заявку студента и не указываем контакты родителей и класс, то падает ошибка 500. (через action)

# Как нужно делать?

Необходимо обработать ошибку.
Сделать обязательным заполнение учебного класса, проходит без него сейчас.
Подумать как мы сможем модифицировать данный экшн.

# Где?

src/potential_user/admin.py

**Comment by MrGosling** [comment]
Ловить 500, если пытаешься одобрить заявку без контактов представителей.

**Comment by OsKaLis** [comment]
Предложу свой вариант:
1) Добавить код  src/potential_user/admin.py c 40 строчки
@admin.action(description='Подтвердить выбранные заявки')
    def approve_applications(self, request, queryset):
        """Перевести все выбранные заявки в статус 'Подтверждено'."""
        for query in queryset:
            if (
                    query.study_class_id is not None and
                    query.parents_contacts is not None
                ):
                query.approved = True
                query.save()
_Пояснение_
Так заявки которые не имеют класса и контакты родителей не зарегистрируются пока не будет внесены значения
2) Нужно  как то информировать ?! Хотя когда заявка не пройдёт пользователь скорей пойдёт в каждую и их просмотрит и как следствие внесёт нужное ?!

**Comment by OsKaLis** [comment]
## Свой вариант версия 2
```
@admin.action(description='Подтвердить выбранные заявки')
    def approve_applications(self, request, queryset):
        """Перевести все выбранные заявки в статус 'Подтверждено'."""
        application: bool = False
        for query in queryset:
            if (
                query.study_class_id is not None and
                query.parents_contacts is not None
            ):
                query.approved = True
                query.save()
            else:
                application = True
        if application:
            text = f'Оставшиеся заявки не заполнены все поля?'
            self.message_user(request, text )
"src/potential_user/admin.py" 55L, 1946B
```
Жду конструктивной критики !?

**Comment by KonstantinRaikhert** [comment]
> ## Свой вариант версия 2
> ```
> @admin.action(description='Подтвердить выбранные заявки')
>     def approve_applications(self, request, queryset):
>         """Перевести все выбранные заявки в статус 'Подтверждено'."""
>         application: bool = False
>         for query in queryset:
>             if (
>                 query.study_class_id is not None and
>                 query.parents_contacts is not None
>             ):
>                 query.approved = True
>                 query.save()
>             else:
>                 application = True
>         if application:
>             text = f'Оставшиеся заявки не заполнены все поля?'
>             self.message_user(request, text )
> "src/potential_user/admin.py" 55L, 1946B
> ```
> 
> Жду конструктивной критики !?

Вообще смотрится очень хорошо, попробуем ПР?)

**Comment by OsKaLis** [comment]
ПР? я правильно понимаю сделать ветку с  ( Pull request )  этой проблемы чтобы смержить ?

**Comment by KonstantinRaikhert** [comment]
> ПР? я правильно понимаю сделать ветку с ( Pull request ) этой проблемы чтобы смержить ?

Ага
