### ISSUE TITLE
Баг в админке при переходе через breadcrumbs

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#172]
# Где был обнаружен баг ?

В админке при всех переходах breadcrumbs.

# Скриншоты

![2024-06-27_20-04](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/69113745/51dd68c1-fbdf-451e-ac6d-817d0349ce75)
![2024-06-27_20-04_1](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/69113745/5f7e59d5-636a-42cf-bce3-8bcc3b9eff39)

# Предложения и предположения как исправить

Проблема в CustomAdminSite. Кажется забыли что то переопределить

**Comment by OsKaLis** [comment]
___ИСПРАВЛЕНИЕ___
/core/admin.py
в 7 строчке:
	def get_app_list(self, request):
На это
	def get_app_list(self, request, app_label=None):

___ДОБ_ОПИСАНИЕ___
Ошибку не вызывает но по-моему перенаправляет не правильно ?!

Все запросы:
	https://localhost:8000/admin/schooling/
	https://localhost:8000/admin/admin_user/
	https://localhost:8000/admin/potential_user/
Перенаправляет на (Показывает сразу всё как бута перешли на):
	https://localhost:8000/admin/

**Comment by KonstantinRaikhert** [comment]
> _**ИСПРАВЛЕНИЕ**_ /core/admin.py в 7 строчке: def get_app_list(self, request): На это def get_app_list(self, request, app_label=None):
> 
> _**ДОБ_ОПИСАНИЕ**_ Ошибку не вызывает но по-моему перенаправляет не правильно ?!
> 
> Все запросы: https://localhost:8000/admin/schooling/ https://localhost:8000/admin/admin_user/ https://localhost:8000/admin/potential_user/ Перенаправляет на (Показывает сразу всё как бута перешли на): https://localhost:8000/admin/

Создашь пул реквест с фиксом?

Возможно да, неправильно. Необходимо посмотреть с фиксом

**Comment by OsKaLis** [comment]
Хорошо ! Но только в среду смогу.
