### ISSUE TITLE
Баг в валидаторе изменения занятия

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#183]
# Где был обнаружен баг ?

Во время изменения урока у нас есть валидатор, который проверяет пересечения по времени с другими занятия данной пары ученика и учителя. Но проблема в том, что теперь этот валидатор вообще не даёт ничего изменить

# Скриншоты

![2024-07-21_21-43](https://github.com/user-attachments/assets/923fff15-922d-4260-aff9-3e348966567a)

# Предложения и предположения как исправить

Находится в src/schooling/form_validators.py

Думаю необходимо поправить проверку. Один из вариантов - исключать из проверки данный инстанс урока.

**Comment by KonstantinRaikhert** [comment]
@OsKaLis Приветствую! Есть возможность оперативно поправить?

**Comment by OsKaLis** [comment]
Добрый день ! Думаю да но после обеда !
