### ISSUE TITLE
Подготовить сервер заказчика для прода

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#186]
# Зачем?

Пока только необходимо провести подготовительные процедуры и сделать авторизацию пользователя по ssh ключу

# Как нужно делать?

Что нужно:
1. Создать пользователя и присвоить ему sudo права БЕЗ ВВОДА пароля
2. установить docker и docker-compose, так же добавить в группу sudo
3. реализовать вход по ssh ключу данного пользователя (не root)

Стучать в личку, дам пароль для root 

# Где?

46.8.210.120

**Comment by kudralexandr** [comment]
Done
Ключи и пароли направлены в личку пачки
[Отчет по задаче #186.pdf](https://github.com/user-attachments/files/16397350/186.pdf)

**Comment by KonstantinRaikhert** [comment]
@kudralexandr Не против следующей таской настроить уже непосредственно доставку нашего приложения?

**Comment by kudralexandr** [comment]
@KonstantinRaikhert , абсолютно не против

**Comment by KonstantinRaikhert** [comment]
Задача выполнена
