### ISSUE TITLE
Провести ревизию по валидации сущностей в админке

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#192]
# Зачем?

Нам нужно понять, где мы еще можем оградить пользователя (администратора) в вводе данных, чтобы это не вызывало коллапса приложения.
 
# Как нужно делать?

Необходимо пробежаться по действующим валидаторам (в формах и моделях) и определить, где можно еще добавить (согласно диаграмме).
Составть список (можно оставить TODO в коде), и можно часть валидаторов сразу взять в работу

# Где?

src/schooling

**Comment by valerashankorenko** [comment]
Предложения по улучшению валидации

1.Валидация даты и времени:
Можно добавить проверку, чтобы дата и время начала урока были в будущем. Это предотвратит создание занятий в прошлом, которые не имеют практического смысла и могут запутать пользователей.

2.Ограничения на длительность урока:
Можно установить минимальную и максимальную длительность урока, чтобы предотвратить создание аномально коротких или длинных уроков, что может быть ошибкой ввода.

3.Валидация номера телефона:
Поскольку мы используем PhoneNumberField, нужно убедиться, что он корректно настроен на прием только валидных номеров. Можно добавить дополнительные проверки формата номера в зависимости от страны.

4.Уникальные имена уроков:
Можно сделать, чтобы названия уроков были уникальными в пределах одного дня или учебного заведения, чтобы избежать путаницы.

5.Валидация состояния учеников и преподавателей:
Возможно добавление проверок на активность аккаунта учеников и преподавателей перед назначением уроков. Например, не разрешать назначать уроки приостановленным аккаунтам.

6.Лимиты на количество учеников и учителей в классах:
В модели StudyClass можно ввести проверки на максимальное количество учеников, а в модели Teacher — на максимальное количество классов или предметов, которые может вести один преподаватель.

7.Безопасность данных:
Проверить, что валидаторы обрабатывают исключения, такие как отсутствие необходимых данных, чтобы предотвратить сбои в работе приложения.

**Comment by valerashankorenko** [comment]
> > Предложения по улучшению валидации
> 
> > 
> 
> > 1.Валидация даты и времени: Можно добавить проверку, чтобы дата и время начала урока были в будущем. Это предотвратит создание занятий в прошлом, которые не имеют практического смысла и могут запутать пользователей.
> 
> > 
> 
> > 2.Ограничения на длительность урока: Можно установить минимальную и максимальную длительность урока, чтобы предотвратить создание аномально коротких или длинных уроков, что может быть ошибкой ввода.
> 
> > 
> 
> > 3.Валидация номера телефона: Поскольку мы используем PhoneNumberField, нужно убедиться, что он корректно настроен на прием только валидных номеров. Можно добавить дополнительные проверки формата номера в зависимости от страны.
> 
> > 
> 
> > 4.Уникальные имена уроков: Можно сделать, чтобы названия уроков были уникальными в пределах одного дня или учебного заведения, чтобы избежать путаницы.
> 
> > 
> 
> > 5.Валидация состояния учеников и преподавателей: Возможно добавление проверок на активность аккаунта учеников и преподавателей перед назначением уроков. Например, не разрешать назначать уроки приостановленным аккаунтам.
> 
> > 
> 
> > 6.Лимиты на количество учеников и учителей в классах: В модели StudyClass можно ввести проверки на максимальное количество учеников, а в модели Teacher — на максимальное количество классов или предметов, которые может вести один преподаватель.
> 
> > 
> 
> > 7.Безопасность данных: Проверить, что валидаторы обрабатывают исключения, такие как отсутствие необходимых данных, чтобы предотвратить сбои в работе приложения.
> 
> 
> 
> Спасибо! Нарежу таски. Есть желание взять в работу определенные?

Могу взять любые. Я на все эти поправки почти написал код)

**Comment by valerashankorenko** [comment]
первые три пункта готовы

**Comment by KonstantinRaikhert** [comment]
> первые три пункта готовы, остальные еще в работе

Отлично! Тогда создам таску и ты к ней уже выкатишь ПР) Спасибо!)
