### ISSUE TITLE
Поправить в админке локализацию

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#196]
# Где был обнаружен баг ?

Нам нужно, чтобы было написано на русском, так будет красивее.

# Скриншоты

![2024-08-01_11-21](https://github.com/user-attachments/assets/9fb183a1-7c9a-4bfd-bd11-b69cef512c91)

# Предложения и предположения как исправить

Скорее всего метод __str__ в модели

**Comment by valerashankorenko** [comment]
Давай я поправлю)

**Comment by valerashankorenko** [comment]
Исправлено)

**Comment by valerashankorenko** [comment]
не могу найти где поправить
![Снимок экрана от 2024-08-09 20-07-01](https://github.com/user-attachments/assets/e83771e8-5670-4e89-999d-74c759bc2864)
