### ISSUE TITLE
Поправить баг в сигналах при выборе флага занятие прошло вываливается ошибка

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#198]
# Где был обнаружен баг ?

Возможно это связано с тем, что у нас есть функционал опроса юзеров. И если оба нажимают галочку, что занятие прошло. То флаг сигналом переводится в True. Но может быть ситуцация, когда администратору необходимо вручную это сделать. Поэтому нужно поправить.

# Скриншоты

![2024-08-01_11-54](https://github.com/user-attachments/assets/d4220059-f40e-4aa3-87aa-eee9c0f3860f)
![2024-08-01_11-55](https://github.com/user-attachments/assets/90f59e00-4fdc-4ebc-908d-5623fb2f720f)

# Предложения и предположения как исправить

Нужно взглянуть на signals_bot, возможно можно сделать так, чтобы при ручном нажатии сообщение не отправлялось.

**Comment by OsKaLis** [comment]
В файле: Goodstart_telegram_bot\src\schooling\signals_bot.py

Когда не меняется время или препод нет переменной [message_text]
И как следствие в 214 строчке кода (message_text=message_text,)
вызывает ошибку (cannot access local variable 'message_text' where it is not associated with a value)

Предлогаемое решение:
в функции (msg_change_lesson) файла описаный выше
добавить строчку [message_text = None]

и обвязать:
```
if message_text is not None:
    await gather_send_messages_to_users(
        chat_ids=chat_ids,
        message_text=message_text,
        reply_markup=reply_markup,
    )
```
?!

**Comment by KonstantinRaikhert** [comment]
@kudralexandr Сразу назначаю, вдруг устал от настройки сервера)
