### ISSUE TITLE
Ошибка удаления занятия, конфликт в асинхронности

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#199]
# Где был обнаружен баг ?

У нас есть сигнал `async def delete_lesson_and_send_msg`. Тут конфликт во время удаления занятия возникает. Т.е. корутина асинхронная по отправке сообщения. А удаление занятие происходит на синхронном уровне. Нужно поправить sync_to_async

# Скриншоты

![2024-08-01_12-08](https://github.com/user-attachments/assets/db5cd83c-32bf-452d-adf1-589f3787c33b)
![2024-08-01_12-08_1](https://github.com/user-attachments/assets/ef41eacf-7805-4bdd-9e5d-1350630fd967)

# Предложения и предположения как исправить

нужно переписать сигнал, возможно декомпозировать.
Важно! Пользователи должны создаваться реальные, чтобы отловить баг

**Comment by KonstantinRaikhert** [comment]
@valerashankorenko У Валерии не получилось, возьмешь?

**Comment by valerashankorenko** [comment]
> @valerashankorenko У Валерии не получилось, возьмешь?

Да давай возьму. Завтра берусь плотно за этот баг)
