### ISSUE TITLE
Добавить кнопку назад при переносе и отмене занятия

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#217]
# Зачем?

Нам нужна эта кнопка чтобы вернуться к списку занятий, если вдруг выбрано не то занятие

# Как нужно делать?

Добавить обработчик
![2024-08-15_17-50](https://github.com/user-attachments/assets/8a0e92bb-e292-45ae-b938-1e146135db1d)

# Где?

schooling

**Comment by ViaDo1orosa** [comment]
Наглядные изменения:
Без наведения на кнопку "Назад" 
![image](https://github.com/user-attachments/assets/005abaf5-8750-4493-aa9f-7cfbfab204e9)
С наведением на кнопку "Назад" 
![image](https://github.com/user-attachments/assets/17a7fc23-2ce3-4291-9e5b-3ee7575a3f7e)
