### ISSUE TITLE
Починить запуск приложения

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#25]
# Где был обнаружен баг ?

После добавления Makefile и дополнительных приложений, как оказалось, наше приложение не работает. 

# Скриншоты

При вызове команды make run вылетает ошибка
![2024-05-05_23-09](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/69113745/cbf6a524-804a-4b4b-9687-e7204a7652f6)

# Предложения и предположения как исправить

Проблема добавления Администратора, который наследуется от AbstractUser, проверить правильность наследования. Кажется что-то не указали

**Comment by merkme** [comment]
В рамках ветки Dev у меня тоже не запускалось приложение, поэтому не мог проверить, если сейчас приложение можно запустить, обязательно исправлю и протестирую.
