### ISSUE TITLE
Реализация сущности StudyClass с фикстурами заполнения в БД

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#27]
# Зачем?

Необходимо реализовать сущность - учебный класс (1 класс, 11 класс).
Вместе с этим нужно написать фикстуры сразу в миграции для удобства.

# Как нужно делать?

Для начала необходимо реализовать модель в schooling
Добавить отображение в админке
Реализовать кастомную миграцию для заполнения БД. Тут несколько важных моментов: миграция должна иметь удобочитаемое имя и в названии должно быть понятно, что она заполняет, миграция должна быть возвратной (с отменой). Ну и занести все основные школьные предметы. Пример можно подглядеть [тут](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/blob/develop/src/bot/migrations/0008_add_profession.py)

# Где?

src/schooling/models.py

**Comment by KonstantinRaikhert** [comment]
@Mitsushidu Привет! Как твои дела?)

**Comment by Mitsushidu** [comment]
@KonstantinRaikhert Привет, приступил к созданию модели, но всё еще проблемы с тем что не могу создать суперюзера. Ещё долго не мог подключиться к базе данных, пару дней ушло на то чтобы эту проблему решить

**Comment by Mitsushidu** [comment]
@KonstantinRaikhert Только не совсем понял, study_class_name это просто "класс" или это какое-то уникальное название? и study_class_number это номер класса как первый или одиннадцатый?

**Comment by KonstantinRaikhert** [comment]
> @KonstantinRaikhert Только не совсем понял, study_class_name это просто "класс" или это какое-то уникальное название? и study_class_number это номер класса как первый или одиннадцатый? 

Всё проблемы с суперюзером решены, необходимо обновиться с dev.
Study_class_name = Первый класс
Study_class_number = 1
