### ISSUE TITLE
Невозможно создать суперюзера. 

### ISSUE THREAD

**Issue by merkme** [Studio-Yandex-Practicum/Goodstart_telegram_bot#37]
# Где был обнаружен баг ?
При создании супер юзера через python manage.py createsuperuser
Причина бага в том, что нужно переопределить BaseUserManager

# Скриншоты
![image](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/44044107/3e4f31d5-83dc-45f4-9d0d-1b533c9336ab)

# Предложения и предположения как исправить
[Статья №1](https://stackoverflow.com/questions/69292770/how-can-i-make-a-custom-user-model-in-django-without-using-username-field)
[Статья №2](https://heemayl.net/posts/django-custom-user-model-without-username-field-and-using-email-in-place-of-it/)

Так же дополнительно необходимо добавить к fields в файле admin.py приложения admin_user поле Administrator.USERNAME_FIELD, так как в модели мы указали это поле как e-mail. (иначе будет баг с созданием нового админа в админке)

**Comment by KonstantinRaikhert** [comment]
Проблема решена
