### ISSUE TITLE
Реазилация хендлеров с проверком пользователя в БД и стейта на форму регистрации

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#43]
# Зачем?

Начинаем работу по взаимодействию с пользователем.
У нас будет формв регистрации в виде webapp
![2024-05-13_12-58](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/69113745/e5fca6fc-1073-4d7d-807e-9890a25fc618)

Нужно реализовать хендлер с проверкой пользователя в БД и перенапралении на необходимый уровень
![2024-05-13_13-11](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/69113745/404fccfb-10c5-4b04-a53b-2c38a4a7a498)

# Как нужно делать?

- обязательно выполняем в папке handlers
- нужно реализовать проверку пользователя в БД (в Teacher или Student)
- сделать 2 стейта: с предложением зарегистрироваться и с приветствием пользователя

# Где?

src/bot/handlers.py

**Comment by BIXBER** [comment]
@KonstantinRaikhert Доброго времени суток! Не совсем понятно, как организовать расположение кода, так как в вашем задании:


> Как нужно делать?
> - обязательно выполняем в папке handlers --> папка

> Где?
> - src/bot/handlers.py --> файл

Имеется некоторое противоречие.

Подскажите, каким утверждением руководствоваться?

**Comment by KonstantinRaikhert** [comment]
> @KonstantinRaikhert Доброго времени суток! Не совсем понятно, как организовать расположение кода, так как в вашем задании:
> 
> > Как нужно делать?
> > 
> > * обязательно выполняем в папке handlers --> папка
> 
> > Где?
> > 
> > * src/bot/handlers.py --> файл
> 
> Имеется некоторое противоречие.
> 
> Подскажите, каким утверждением руководствоваться?

Приветствую!
Имелось ввиду, что мы создадим папку handlers а уже в ней будем реализовывать по смыслу наши скрипты

**Comment by BIXBER** [comment]
Снова нашел недопонимание: так как вы в схеме выше описываете проверку пользователя в БД по полю `username`, а в моделях для сверки, которые вы указываете (`Teacher` и `Student`) нет такого поля, то какое поле использовать для сверки пользователя в БД в итоге?

**Comment by KonstantinRaikhert** [comment]
> @KonstantinRaikhert, cнова нашел недопонимание: так как вы в схеме выше описываете проверку пользователя в БД по полю `username`, а в моделях для сверки, которые вы указываете (`Teacher` и `Student`) нет такого поля, то какое поле использовать для сверки пользователя в БД в итоге?

Сейчас мержу BPNM, и там уже указан telegram ID. Судя по всему вы уже договорились)
Да, необходимо получать telegram ID пользователя.
Кстати может декомпозировать таску?

**Comment by BIXBER** [comment]
> > @KonstantinRaikhert, cнова нашел недопонимание: так как вы в схеме выше описываете проверку пользователя в БД по полю `username`, а в моделях для сверки, которые вы указываете (`Teacher` и `Student`) нет такого поля, то какое поле использовать для сверки пользователя в БД в итоге?
> 
> Сейчас мержу BPNM, и там уже указан telegram ID. Судя по всему вы уже договорились) Да, необходимо получать telegram ID пользователя. Кстати может декомпозировать таску?

Ну да, считаю это верным решением (использовать Telegram ID поле). Если потребуется декомпозиция - я дам знать.
