### ISSUE TITLE
Реализовать отображение статики панели администраторов

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#50]
# Зачем?

После добавления функционала запуска бота через asgi.py у нас слетело отображение статити, т.к. обычно для этого используется сторонний сервер (типа nginx)

# Как нужно делать?

Определить раздачу статитики

# Где?

infra

**Comment by KonstantinRaikhert** [comment]
@DBratkov Привет! От тебя ожидать ПР?) Или снимать задачу

**Comment by DBratkov** [comment]
Привет, планирую конечно ее сделать. Просто на работе завал, по ночам только занимаюсь

**Comment by KonstantinRaikhert** [comment]
> Привет, планирую конечно ее сделать. Просто на работе завал, по ночам только занимаюсь

На всякий случай интересуюсь)
