### ISSUE TITLE
Реализовать github workflow для сборки докер образа на github packages

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#52]
# Зачем?

Для непрерывной интеграции нам нужно сделать автоматическую сборку образа нашего приложения и пуш его сюда на гитхаб при помощи встроенного сервиса Github packages

UPD: предыдущий разработчик снялся с задачи. Его PR #59 

# Как нужно делать?

Предалагаю посмотреть на [пример](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/blob/develop/.github/workflows/build-and-push-github-packages.yml)

# Где?

.github/workfows/

**Comment by KonstantinRaikhert** [comment]
@evgeny-fastunov Привет! Видел коммент в ПР?) Или снимать задачу?

**Comment by evgeny-fastunov** [comment]
Привет! Снимите задачу, к сожалению нет времени заниматься. Спасибо за поддержку!
