### ISSUE TITLE
Написание утилиты перевода из заявок в пользователей

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#61]
# Зачем?

В админке реализован флаг - approved (скрин пока без статики). При его выборе должна срабатывать утилита, которая из заявки создаёт сущность ученик или преподаватель.
![2024-05-20_21-13](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/69113745/9f5ace14-71cd-4b14-bd0e-2014fad424e8)

# Как нужно делать?

- реализовать утилиту
- возможно нужен сигнал, который реагирует на изменение флага (тут подумать)

# Где?

src/core/utils/

**Comment by KonstantinRaikhert** [comment]
@nesterovv89 Привет!) Ты сделаешь задачу?

**Comment by nesterovv89** [comment]
> @nesterovv89 Привет!) Ты сделаешь задачу?

Привет, ага, в процессе)
