### ISSUE TITLE
Функция переноса объекта из Заявок в Пользователя не работает

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#67]
# Где был обнаружен баг ?

У нас есть функционал, который обрабатывает заявку на регистрацию и при указании флага approve должна переводить либо в ученика либо в преподавателя.
Обнаружено, что не работает.

src/core/utils.py

create_user_from_application

# Предложения и предположения как исправить

Нужно посмотреть, что в сигналах отрабатывается..

**Comment by sergey-xx** [comment]
добавил ветку
