### ISSUE TITLE
Добавить ссылку на политику по обработке персональных данных

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#68]
# Зачем?

Как верно было подмечено на созвоне - необходимо указать ссылку.

https://goodstart-education.ru/privacy

# Как нужно делать?

Поправить django-template с примерным текстом: "Нажимая на кнопку Зарегистирироваться Вы соглашаетесь с политикой по обработке персональных данных.

# Где?

src/templates/registration/registration_form.html

**Comment by KonstantinRaikhert** [comment]
@Tincampy Привет! Возникли сложности с таской?

**Comment by Tincampy** [comment]
Нет, просто только в вс добрался до компьютера и первый раз разворачивал, потом на сутки по работе уехал, до завтра включительно закрою

> @Tincampy Привет! Возникли сложности с таской?
