### ISSUE TITLE
Обработка кейса отказа от регистрации и открытия webb app

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#69]
# Зачем?

Необходимо, как на диаграмме реализовать отказ от регистрации или вызов формы регистрации при положительном ответе
![2024-05-24_19-10](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/69113745/bc105ef7-cd80-471b-8004-ce7e714365d5)

# Как нужно делать?

Реализация хендлера с инлайн клавиатурой. 
Добавление ссылки на форму регистрации (посмотреть в документации https://docs.python-telegram-bot.org/en/stable/examples.webappbot.html)

# Где?

src/bot/handlers

**Comment by alexpunder** [comment]
@KonstantinRaikhert
Не совсем могу понять что является "возвратом в главное меню", если при команде `/start` мы пытаемся найти пользователя по `telegram_id` в нашей БД и если его нет, то получаем окно с сообщением и кнопками `Зарегистрироваться` и `Отказаться`. Не соображу, куда в таком случае должен перенаправляться пользователь при нажатии на `Отказаться`

![Image](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/131157269/c42ac590-2113-4aba-9000-c62e998084c7)

**Comment by KonstantinRaikhert** [comment]
> @KonstantinRaikhert
> Не совсем могу понять что является "возвратом в главное меню", если при команде `/start` мы пытаемся найти пользователя по `telegram_id` в нашей БД и если его нет, то получаем окно с сообщением и кнопками `Зарегистрироваться` и `Отказаться`. Не соображу, куда в таком случае должен перенаправляться пользователь при нажатии на `Отказаться`
> 
> ![Image](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/131157269/c42ac590-2113-4aba-9000-c62e998084c7)
> 
> 

Хм, действительно неправильно. Может сразу поправить Bpmn и оставить кнопку зарегистрироваться с вызовом web app?
Согласен, как то все же нелогично усложнять действия
