### ISSUE TITLE
Проработать Bpmn диаграмму для кейса взаимодействия с преподавателем на основе схемы в Miro

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#73]
# Что нужно описать?

Нам нужно для упрощения разработки проработать данный вид диаграммы с необходиыми шагами взаимодействия.
Пример - [кейс регистрации пользователя](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/blob/dev/docs/bpmn/registration.jpg)
Для работы предлагается онлай редактор - bpmn.io/
Схема в [Miro](https://miro.com/app/board/uXjVKTz7zLw=/)

![2024-05-26_13-04_1](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/69113745/708062f9-0eb9-4fb5-90a5-243267595f04)

# Где?

docs

**Comment by alexpunder** [comment]
@KonstantinRaikhert 
заметил небольшую опечатку
![some_bug](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/131157269/5344b24b-9010-4cc4-aecf-9eb79df4f6da)
