### ISSUE TITLE
Проработать Bpmn диаграмму для кейса взаимодействия с учеником на основе схемы в Miro

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#74]
# Что нужно описать?

Нам нужно для упрощения разработки проработать данный вид диаграммы с необходимыми шагами взаимодействия.
Пример - [кейс регистрации пользователя](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/blob/dev/docs/bpmn/registration.jpg)
Для работы предлагается онлай редактор - bpmn.io/
Схема в [Miro](https://miro.com/app/board/uXjVKTz7zLw=/)

![2024-05-26_13-04](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/69113745/0370d020-43d9-4cd0-8629-d603b7c770d8)

# Где?

docs

**Comment by KonstantinRaikhert** [comment]
@frailtynine Привет! Есть успехи?

**Comment by frailtynine** [comment]
@KonstantinRaikhert Привет, да, я сегодня дорисую и отправлю.
