### ISSUE TITLE
Создание фабрик для Lesson

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#85]
# Зачем?

Нам нужно создать по 3-4 урока на каждого ученика и учителя. Важный момент - по временной составляющей должны быть на неделю, чтобы потом смогли просматривать на странице webapp 
![2024-05-30_20-05](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/69113745/b85ae47b-fcdc-4dd6-a870-34e4ac4d37a9)

# Как нужно делать?

- так же используем factory boy
- так же добавляем в Makefile команду и лучше создать отдельную, которая объединит все генерации тестовых - например make fill-db

# Где?

src/schooling/factories

**Comment by shkiperzero** [comment]
Issue не туда улетел? На доске не вижу квадратик.

**Comment by KonstantinRaikhert** [comment]
> Issue не туда улетел? На доске не вижу квадратик.

Пардон. Поправил

**Comment by KonstantinRaikhert** [comment]
@shkiperzero Приветствую! Приступил к реализации?)

**Comment by shkiperzero** [comment]
> @shkiperzero Приветствую! Приступил к реализации?)

В понедельник стартую. В выходные совсем не было времени.

**Comment by shkiperzero** [comment]
@KonstantinRaikhert должны ли все созданные уроки иметь test_lesson = True?

**Comment by KonstantinRaikhert** [comment]
> @KonstantinRaikhert должны ли все созданные уроки иметь test_lesson = True?

Нет, можно сделать test_lesson в количестве 5, остальные False

**Comment by KonstantinRaikhert** [comment]
@shkiperzero Есть успехи?) Таска сейчас немного блокирует реализацию другого функционала

**Comment by shkiperzero** [comment]
> @shkiperzero Есть успехи?) Таска сейчас немного блокирует реализацию другого функционала

Постараюсь сегодня залить ПР
