### ISSUE TITLE
Реализовать endpoint с расписанием занятий

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#89]
# Зачем?

Нужно сделать по аналогии с регистрацией. Выводить пока можно (шаблон) в виде простой таблицы

# Как нужно делать?

- ендпоинт должен формироваться по telegram ID пользователя

# Где?

src/schooling

**Comment by KonstantinRaikhert** [comment]
@serega-zhulanov У Артёма возникли проблемы с аккаунтом. Перехватишь таску?

**Comment by serega-zhulanov** [comment]
Да хорошо)

**Comment by KonstantinRaikhert** [comment]
@serega-zhulanov Есть успехи?

**Comment by KonstantinRaikhert** [comment]
@serega-zhulanov Привет! Если не справляешься, напиши пожалуйста. Таска очень важна и зависла. Может кому то передать?

**Comment by serega-zhulanov** [comment]
Привет! Сегодня отправлю на ревью
