### ISSUE TITLE
Ресерч по FSM (конечные автоматы) и хранение стейтов в Postgres

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#93]
# Зачем?

Нам скоро нужно будет подключать поддержку стейтов в нашем проекте. Для того, чтобы пользователь оставался на своём шаге, если вдруг у нас перезагрузился сервер. 
На более сложных системах используют NoSQL БД, на самых простых pickle файлы (Можно посмотреть в документации к библиотеке).
Я думаю, нам стоит хранить наши состояния в Postgres, проект не нагруженный, небольшой, думаю не стоит усложнять.

Задача ресерча заключается в том, чтобы найти информацию по подключению FSM к postgres (драйвера в боте, методы).

**Comment by frailtynine** [comment]
@KonstantinRaikhert Поресерчил, выводы такие. 

Для джанго есть библиотека [viewflow.fsm](https://docs.viewflow.io/fsm), которая управляет логикой перехода из одного state  в другой и [интегрируется в Django ORM](https://docs.viewflow.io/fsm/models.html). Для ее внедрения нужно будет добавить поле state (Charfield) к моделям пользователей, создать отдельный класс с логикой FSM, включая обновление модели при успешном обновлении стейта, и объект TextChoices с возможными вариантами. Если мы не хотим добавлять новое поле, можно создать отдельную модель, которая будет хранить стейт и пользователя, но я не очень понимаю, какая на этой стадии разработки будет от этого выгода.  

В хэндлерах бота мы просто создаем объект flow на основе класса FSM, в него передаем пользователя и через него работаем со стейтом. 

Хендлеры, которые зависят от стейта, нужно будет объединить в единый хендлер (например, он будет в ), который подключим в классе бота в  методе _build_app. 

Вот как-то так. Я не сталкивался с FSM до этой задачи, поэтому могу в чем-то заблуждаться.

**Comment by KonstantinRaikhert** [comment]
> @KonstantinRaikhert Поресерчил, выводы такие.
> 
> Для джанго есть библиотека [viewflow.fsm](https://docs.viewflow.io/fsm), которая управляет логикой перехода из одного state в другой и [интегрируется в Django ORM](https://docs.viewflow.io/fsm/models.html). Для ее внедрения нужно будет добавить поле state (Charfield) к моделям пользователей, создать отдельный класс с логикой FSM, включая обновление модели при успешном обновлении стейта, и объект TextChoices с возможными вариантами. Если мы не хотим добавлять новое поле, можно создать отдельную модель, которая будет хранить стейт и пользователя, но я не очень понимаю, какая на этой стадии разработки будет от этого выгода.
> 
> В хэндлерах бота мы просто создаем объект flow на основе класса FSM, в него передаем пользователя и через него работаем со стейтом.
> 
> Хендлеры, которые зависят от стейта, нужно будет объединить в единый хендлер (например, он будет в ), который подключим в классе бота в методе _build_app.
> 
> Вот как-то так. Я не сталкивался с FSM до этой задачи, поэтому могу в чем-то заблуждаться.

Хм.. Звучит как план. Можешь оформить эту инфу в ReadMe с примером кода. Чтобы разработчик, который будет реализовывать сразу начал с этого.
