### ISSUE TITLE
Во время заявки ученика реализовать заполнение полей "учебный класс" и "контакты родителей".

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Goodstart_telegram_bot#96]
# Зачем?

Необходимо выбрать способ удобный к заполнению этих данных.
Обнаружена ошибка при автоматическом подтверждении заявки на роль `Учащийся`: нет необходимых полей модели, а именно `study_class_id `и `parents_contacts`
![db_bug](https://github.com/Studio-Yandex-Practicum/Goodstart_telegram_bot/assets/131157269/2eef3389-30c2-4c32-8a28-edf0f3448e01)
Варианты решения проблемы:
1. В самой модели `Student` сделать значения по умолчанию, либо сделать поле необязательным
2. В `core/utils.py` в функции `create_user_from_application` разделить логику создания объекта в зависимости от `instance.role`

# Как нужно делать?

*Как мы выполняем реализацию данной задачи, какие действия нужны для достижения цели.*

# Где?

*Где делаем реализацию задачи, какие сервисы задействованы, ссылка на требования, сcылка на API, скриншоты.*

**Comment by sergey-xx** [comment]
предлагаю 3й путь.
Написать валидатор, который не будет позволять сохранить объект ApplicationForm, если у него:
role == 'ученик' and (not study_class_id or not parents_contacts).
При этом нужно добавить эти поля в модель ApplicationForm (null=True).
Таким образом: 
- пользователь заполняет форму.
- менеджер дополняет заявку
- менеджер аппрувит форму
В итоге на этапе создания ученика все его данные заполнены. Успех!

**Comment by sergey-xx** [comment]
+ для админки можно настроить поля так что бы study_class_id и parents_contacts не отображались для учителя

**Comment by KonstantinRaikhert** [comment]
> @KonstantinRaikhert предлагаю 3й путь. Написать валидатор, который не будет позволять сохранить объект ApplicationForm, если у него: role == 'ученик' and (not study_class_id or not parents_contacts). При этом нужно добавить эти поля в модель ApplicationForm (null=True). Таким образом:
> 
> * пользователь заполняет форму.
> * менеджер дополняет заявку
> * менеджер аппрувит форму
>   В итоге на этапе создания ученика все его данные заполнены. Успех!

Имеешь ввиду из объекта ApplicationForm сохранение в Student. Идея хорошая и написать какой нибудб скрипт js для отображения дополнительных обязательных полей в админке ApplicationForm, если роль ученик.

**Comment by sergey-xx** [comment]
это делается с помощью джанги.
я запилил, но есть проблема

```
$ ruff check src/
warning: `one-blank-line-before-class` (D203) and `no-blank-line-before-class` (D211) are incompatible. Ignoring `one-blank-line-before-class`.
src\potential_user\models.py:
  52:24 DJ001 Avoid using `null=True` on string-based fields such as `CharField`

Found 1 error.
(wenv) 
```

**Comment by KonstantinRaikhert** [comment]
> это делается с помощью джанги. я запилил, но есть проблема
> 
> ```
> $ ruff check src/
> warning: `one-blank-line-before-class` (D203) and `no-blank-line-before-class` (D211) are incompatible. Ignoring `one-blank-line-before-class`.
> src\potential_user\models.py:
>   52:24 DJ001 Avoid using `null=True` on string-based fields such as `CharField`
> 
> Found 1 error.
> (wenv) 
> ```
> 
> я могу добавить в ignore?

Да, это можно
